{{- if .Values.config.create }}
{{- $data := dict }}
{{- include "honua.nonEmptyEnv" (dict "src" .Values.config.env "dst" $data) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "honua.configmapName" . }}
  labels:
    {{- include "honua.labels" . | nindent 4 }}
{{- if gt (len $data) 0 }}
data:
  {{- range $key, $value := $data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
