apiVersion: v1
kind: Service
metadata:
  name: {{ include "honua.fullname" . }}
  labels:
    {{- include "honua.labels" . | nindent 4 }}
  {{- if or .Values.service.annotations .Values.metrics.serviceAnnotations.enabled }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.metrics.serviceAnnotations.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.targetPort | quote }}
    prometheus.io/path: {{ .Values.metrics.serviceAnnotations.path | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "honua.selectorLabels" . | nindent 4 }}
