name: Security

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
  schedule:
    - cron: '0 6 * * 1'

permissions:
  contents: read

jobs:
  trivy:
    permissions:
      contents: read
      security-events: write # Upload Trivy SARIF.
    uses: honua-io/.github/.github/workflows/reusable-trivy.yml@e26b67e904f2c23796fe677d267d73188a764545 # v0.36.0 Trivy workflow snapshot
    with:
      scan-type: fs

  scorecard:
    permissions:
      contents: read
      actions: read
      security-events: write # Upload Scorecard SARIF.
      id-token: write # Publish results to OpenSSF on trunk.
    uses: honua-io/.github/.github/workflows/reusable-scorecard.yml@e26b67e904f2c23796fe677d267d73188a764545 # v2.4.4 Scorecard workflow snapshot

  iac:
    permissions:
      contents: read
      security-events: write # Upload Checkov SARIF.
    uses: honua-io/.github/.github/workflows/reusable-iac-scan.yml@e26b67e904f2c23796fe677d267d73188a764545 # v12 Checkov workflow snapshot
    with:
      directory: "."
      framework: "helm"
